buf_map("n", ".", ": <c-r><c-a><s-left><left>")
buf_map("n", "cb<space>", ":Git branch  <c-r><c-a><s-left><left>")
buf_map("n", "co<space>", ":Git checkout  <c-r><c-a><s-left><left>")
buf_map("n", "cot", ":Git checkout --track <c-r><c-a><cr>")
buf_map("n", "A", ":Git checkout -b  <c-r><c-a><s-left><left>")
buf_map("n", "D", ":Git branch  <c-r><c-a><s-left><left>")
buf_map("n", "R", ":Git branch -m <c-r><c-a> <c-r><c-a>")
buf_map("n", "rb", ":Git rebase <c-r><c-a><cr>")
buf_map("n", "mf", ":Git merge <c-r><c-a><cr>")
